---
version: "3.5"

services:
  docker-daemon:
    image: docker:19.03.0-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""

  b2flow-engine-builder:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      B2FLOW__DAG__JOB__NAME: job1
      B2FLOW__IMAGE__TAG: 1
      B2FLOW__IMAGE__NAME: x-team_x-project_x-dag_job1
      B2FLOW__STORAGE__TYPE: 'gcs'
      B2FLOW__STORAGE__S3__ACCESS_KEY_ID: 'key_id'
      B2FLOW__STORAGE__S3__SECRET_KEY_ID: 'secret_id'
      B2FLOW__STORAGE__S3__REGION: 'us-west1'
      B2FLOW__STORAGE__S3__BUCKET: 'bucket-name'
      B2FLOW__STORAGE__URI: 's3://bucket-name/dags/source.zip'
      B2FLOW__REGISTRY__GCP__KEYFILE: 'Service Account Encoded base64'
      B2FLOW__BUILDER__CALLBACK__URI: 'https://domain.com/callback?any_query_string=xxxx'
      DOCKER_HOST: "tcp://docker-daemon:2375"